package com.stilllynnthecloset.liboun.playbook

import com.stilllynnthecloset.liboun.model.Weighted

/**
 * NamePlaybook - TODO: Documentation
 *
 * Created by Lynn on 5/4/23
 */
public object NamePlaybook {
    public val locationNames1: List<Weighted<String>> = listOf(
        Weighted(1, "Infinite"),
        Weighted(1, "Free"),
        Weighted(1, "Ardent"),
        Weighted(1, "Traverse"),
        Weighted(1, "Bryn"),
        Weighted(1, "Orbital"),
        Weighted(1, "Escapist"),
        Weighted(1, "Border"),
        Weighted(1, "Intrinsic"),
        Weighted(1, "Extrinsic"),
        Weighted(1, "Prin"),
        Weighted(1, "Phen"),
        Weighted(1, "Hwey"),
        Weighted(1, "Aspic"),
        Weighted(1, "Enigmatic"),
        Weighted(1, "Triune"),
        Weighted(1, "Sable"),
        Weighted(1, "Choral"),
        Weighted(1, "Juggernauthene"),
        Weighted(1, "Eocenic"),
        Weighted(1, "Shameful"),
        Weighted(1, "Vaid-Hul"),
        Weighted(1, "Epsilonic"),
        Weighted(1, "Labyrinthine"),
        Weighted(1, "Agnostic"),
        Weighted(1, "Far"),
        Weighted(1, "Inferior"),
        Weighted(1, "Planetary"),
        Weighted(1, "Penultimate"),
        Weighted(1, "Anteuniversalian"),
    )

    public val locationNames2: List<Weighted<String>> = listOf(
        Weighted(1, "Verge"),
        Weighted(1, "Hold"),
        Weighted(1, "None"),
        Weighted(1, "Null"),
        Weighted(1, "Highway"),
        Weighted(1, "Threshold"),
        Weighted(1, "Station"),
        Weighted(1, "Calypso"),
        Weighted(1, "Descant"),
        Weighted(1, "Jig"),
        Weighted(1, "Tango"),
        Weighted(1, "Yellowknife"),
        Weighted(1, "Om"),
        Weighted(1, "Phaedra"),
        Weighted(1, "Potamos"),
        Weighted(1, "Bar-Brilliad"),
        Weighted(1, "J’Eridiani"),
        Weighted(1, "Anomie"),
        Weighted(1, "Collapse"),
        Weighted(1, "Collate"),
        Weighted(1, "Resonance"),
        Weighted(1, "Cascade"),
        Weighted(1, "Horizon"),
        Weighted(1, "Arc"),
        Weighted(1, "Fence"),
        Weighted(1, "Tribunal"),
        Weighted(1, "Void"),
        Weighted(1, "Eye"),
        Weighted(1, "Fracture"),
        Weighted(1, "Eyrie"),
    )

    public val npcNames1: List<Weighted<String>> = listOf(
        Weighted(1, "out"),
        Weighted(1, "void"),
        Weighted(1, "ether"),
        Weighted(1, "dock"),
        Weighted(1, "infinite"),
        Weighted(1, "well"),
        Weighted(1, "company"),
        Weighted(1, "union"),
        Weighted(1, "mercenary"),
        Weighted(1, "pirate"),
        Weighted(1, "quiet"),
        Weighted(1, "gun"),
        Weighted(1, "sword"),
        Weighted(1, "glitched"),
        Weighted(1, "pious"),
        Weighted(1, "panicked"),
        Weighted(1, "lonesome"),
        Weighted(1, "wearied"),
        Weighted(1, "free"),
        Weighted(1, "wandering"),
        Weighted(1, "long-Haul"),
        Weighted(1, "hardy"),
        Weighted(1, "infected"),
        Weighted(1, "glow"),
        Weighted(1, "feared"),
        Weighted(1, "passerine"),
        Weighted(1, "damanged"),
        Weighted(1, "planetary"),
        Weighted(1, "luminous"),
        Weighted(1, "freetraveler"),
    )

    public val npcNames2: List<Weighted<String>> = listOf(
        Weighted(1, "laborer"),
        Weighted(1, "trader"),
        Weighted(1, "longshoreman"),
        Weighted(1, "conspiracy-theorist"),
        Weighted(1, "outlaw"),
        Weighted(1, "witch"),
        Weighted(1, "wizard"),
        Weighted(1, "pilot"),
        Weighted(1, "mechanic"),
        Weighted(1, "navigator"),
        Weighted(1, "tough"),
        Weighted(1, "researcher"),
        Weighted(1, "priest"),
        Weighted(1, "cook"),
        Weighted(1, "negotiator"),
        Weighted(1, "representative"),
        Weighted(1, "watcher"),
        Weighted(1, "dancer"),
        Weighted(1, "rookie"),
        Weighted(1, "assassin"),
        Weighted(1, "soldier"),
        Weighted(1, "lamp-lighter"),
        Weighted(1, "cultist"),
        Weighted(1, "judge"),
        Weighted(1, "remnant"),
        Weighted(1, "exile"),
        Weighted(1, "runaway"),
        Weighted(1, "indenture"),
        Weighted(1, "machine"),
        Weighted(1, "god"),
    )
}
