package com.stilllynnthecloset.liboun.playbook

import com.stilllynnthecloset.liboun.model.NpcAdjective
import com.stilllynnthecloset.liboun.model.NpcType
import com.stilllynnthecloset.liboun.model.PortAdjective
import com.stilllynnthecloset.liboun.model.PortType
import com.stilllynnthecloset.liboun.model.Weighted

/**
 * NamePlaybook - TODO: Documentation
 *
 * Created by Lynn on 5/4/23
 */
internal object NamePlaybook {
    val locationNames1: List<Weighted<PortAdjective>> = listOf(
        Weighted(1, PortAdjective("Infinite")),
        Weighted(1, PortAdjective("Free")),
        Weighted(1, PortAdjective("Ardent")),
        Weighted(1, PortAdjective("Traverse")),
        Weighted(1, PortAdjective("Bryn")),
        Weighted(1, PortAdjective("Orbital")),
        Weighted(1, PortAdjective("Escapist")),
        Weighted(1, PortAdjective("Border")),
        Weighted(1, PortAdjective("Intrinsic")),
        Weighted(1, PortAdjective("Extrinsic")),
        Weighted(1, PortAdjective("Prin")),
        Weighted(1, PortAdjective("Phen")),
        Weighted(1, PortAdjective("Hwey")),
        Weighted(1, PortAdjective("Aspic")),
        Weighted(1, PortAdjective("Enigmatic")),
        Weighted(1, PortAdjective("Triune")),
        Weighted(1, PortAdjective("Sable")),
        Weighted(1, PortAdjective("Choral")),
        Weighted(1, PortAdjective("Juggernauthene")),
        Weighted(1, PortAdjective("Eocenic")),
        Weighted(1, PortAdjective("Shameful")),
        Weighted(1, PortAdjective("Vaid-Hul")),
        Weighted(1, PortAdjective("Epsilonic")),
        Weighted(1, PortAdjective("Labyrinthine")),
        Weighted(1, PortAdjective("Agnostic")),
        Weighted(1, PortAdjective("Far")),
        Weighted(1, PortAdjective("Inferior")),
        Weighted(1, PortAdjective("Planetary")),
        Weighted(1, PortAdjective("Penultimate")),
        Weighted(1, PortAdjective("Anteuniversalian")),
    )

    val locationNames2: List<Weighted<PortType>> = listOf(
        Weighted(1, PortType("Verge")),
        Weighted(1, PortType("Hold")),
        Weighted(1, PortType("None")),
        Weighted(1, PortType("Null")),
        Weighted(1, PortType("Highway")),
        Weighted(1, PortType("Threshold")),
        Weighted(1, PortType("Station")),
        Weighted(1, PortType("Calypso")),
        Weighted(1, PortType("Descant")),
        Weighted(1, PortType("Jig")),
        Weighted(1, PortType("Tango")),
        Weighted(1, PortType("Yellowknife")),
        Weighted(1, PortType("Om")),
        Weighted(1, PortType("Phaedra")),
        Weighted(1, PortType("Potamos")),
        Weighted(1, PortType("Bar-Brilliad")),
        Weighted(1, PortType("J’Eridiani")),
        Weighted(1, PortType("Anomie")),
        Weighted(1, PortType("Collapse")),
        Weighted(1, PortType("Collate")),
        Weighted(1, PortType("Resonance")),
        Weighted(1, PortType("Cascade")),
        Weighted(1, PortType("Horizon")),
        Weighted(1, PortType("Arc")),
        Weighted(1, PortType("Fence")),
        Weighted(1, PortType("Tribunal")),
        Weighted(1, PortType("Void")),
        Weighted(1, PortType("Eye")),
        Weighted(1, PortType("Fracture")),
        Weighted(1, PortType("Eyrie")),
    )

    val npcNames1: List<Weighted<NpcAdjective>> = listOf(
        Weighted(1, NpcAdjective("out")),
        Weighted(1, NpcAdjective("void")),
        Weighted(1, NpcAdjective("ether")),
        Weighted(1, NpcAdjective("dock")),
        Weighted(1, NpcAdjective("infinite")),
        Weighted(1, NpcAdjective("well")),
        Weighted(1, NpcAdjective("company")),
        Weighted(1, NpcAdjective("union")),
        Weighted(1, NpcAdjective("mercenary")),
        Weighted(1, NpcAdjective("pirate")),
        Weighted(1, NpcAdjective("quiet")),
        Weighted(1, NpcAdjective("gun")),
        Weighted(1, NpcAdjective("sword")),
        Weighted(1, NpcAdjective("glitched")),
        Weighted(1, NpcAdjective("pious")),
        Weighted(1, NpcAdjective("panicked")),
        Weighted(1, NpcAdjective("lonesome")),
        Weighted(1, NpcAdjective("wearied")),
        Weighted(1, NpcAdjective("free")),
        Weighted(1, NpcAdjective("wandering")),
        Weighted(1, NpcAdjective("long-Haul")),
        Weighted(1, NpcAdjective("hardy")),
        Weighted(1, NpcAdjective("infected")),
        Weighted(1, NpcAdjective("glow")),
        Weighted(1, NpcAdjective("feared")),
        Weighted(1, NpcAdjective("passerine")),
        Weighted(1, NpcAdjective("damanged")),
        Weighted(1, NpcAdjective("planetary")),
        Weighted(1, NpcAdjective("luminous")),
        Weighted(1, NpcAdjective("freetraveler")),
    )

    val npcNames2: List<Weighted<NpcType>> = listOf(
        Weighted(1, NpcType("laborer")),
        Weighted(1, NpcType("trader")),
        Weighted(1, NpcType("longshoreman")),
        Weighted(1, NpcType("conspiracy-theorist")),
        Weighted(1, NpcType("outlaw")),
        Weighted(1, NpcType("witch")),
        Weighted(1, NpcType("wizard")),
        Weighted(1, NpcType("pilot")),
        Weighted(1, NpcType("mechanic")),
        Weighted(1, NpcType("navigator")),
        Weighted(1, NpcType("tough")),
        Weighted(1, NpcType("researcher")),
        Weighted(1, NpcType("priest")),
        Weighted(1, NpcType("cook")),
        Weighted(1, NpcType("negotiator")),
        Weighted(1, NpcType("representative")),
        Weighted(1, NpcType("watcher")),
        Weighted(1, NpcType("dancer")),
        Weighted(1, NpcType("rookie")),
        Weighted(1, NpcType("assassin")),
        Weighted(1, NpcType("soldier")),
        Weighted(1, NpcType("lamp-lighter")),
        Weighted(1, NpcType("cultist")),
        Weighted(1, NpcType("judge")),
        Weighted(1, NpcType("remnant")),
        Weighted(1, NpcType("exile")),
        Weighted(1, NpcType("runaway")),
        Weighted(1, NpcType("indenture")),
        Weighted(1, NpcType("machine")),
        Weighted(1, NpcType("god")),
    )
}
